package slack

// Auto-generated by internal/cmd/genmethods/genmethods.go. DO NOT EDIT!

import (
	"context"
	"net/url"
	"strconv"
	"strings"

	"github.com/lestrrat-go/slack/objects"
	"github.com/pkg/errors"
)

var _ = strconv.Itoa
var _ = strings.Index
var _ = objects.EpochTime(0)

// AppsPermissionsScopesListCall is created by AppsPermissionsScopesService.List method call
type AppsPermissionsScopesListCall struct {
	service *AppsPermissionsScopesService
}

// List creates a AppsPermissionsScopesListCall object in preparation for accessing the apps.permissions.scopes.list endpoint
func (s *AppsPermissionsScopesService) List() *AppsPermissionsScopesListCall {
	var call AppsPermissionsScopesListCall
	call.service = s
	return &call
}

// ValidateArgs checks that all required fields are set in the AppsPermissionsScopesListCall object
func (c *AppsPermissionsScopesListCall) ValidateArgs() error {
	return nil
}

// Values returns the AppsPermissionsScopesListCall object as url.Values
func (c *AppsPermissionsScopesListCall) Values() (url.Values, error) {
	if err := c.ValidateArgs(); err != nil {
		return nil, errors.Wrap(err, `failed validation`)
	}
	v := url.Values{}
	v.Set(`token`, c.service.token)
	return v, nil
}

// Do executes the call to access apps.permissions.scopes.list endpoint
func (c *AppsPermissionsScopesListCall) Do(ctx context.Context) error {
	const endpoint = "apps.permissions.scopes.list"
	v, err := c.Values()
	if err != nil {
		return err
	}
	var res struct {
		objects.GenericResponse
	}
	if err := c.service.client.postForm(ctx, endpoint, v, &res); err != nil {
		return errors.Wrap(err, `failed to post to apps.permissions.scopes.list`)
	}
	if !res.OK {
		return errors.New(res.Error.String())
	}

	return nil
}

// FromValues parses the data in v and populates `c`
func (c *AppsPermissionsScopesListCall) FromValues(v url.Values) error {
	var tmp AppsPermissionsScopesListCall
	*c = tmp
	return nil
}
